
var Stockfish = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


function d(){k.buffer!=l&&t(k.buffer);return aa}function v(){k.buffer!=l&&t(k.buffer);return ba}function w(){k.buffer!=l&&t(k.buffer);return ca}function y(){k.buffer!=l&&t(k.buffer);return da}function ea(){k.buffer!=l&&t(k.buffer);return fa}null;var z;z||(z=typeof Stockfish !== 'undefined' ? Stockfish : {});var ha,ia;z.ready=new Promise(function(a,b){ha=a;ia=b});null;
(()=>{function a(){if(0<f.length){let g=f.shift();0!=z.ccall("uci_command","number",["string"],[g])?(f.unshift(g),h*=2):h=1;setTimeout(a,h)}}const b=[],c=[],f=[];z.print=g=>{b.push(g)};z.printErr=g=>{c.push(g)};z.message=()=>0<b.length?b.shift():null;z.errMessage=()=>0<c.length?c.shift():null;var h=1;z.postMessage=g=>{f.push(g)};z.postRun=()=>{z.postMessage=g=>{f.push(g);1==f.length&&a()};a()}})();
var ja=Object.assign({},z),ka=[],A="./this.program",B=(a,b)=>{throw b;},la="object"==typeof window,C="function"==typeof importScripts,D="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,E=z.ENVIRONMENT_IS_PTHREAD||!1,F="";function ma(a){return z.locateFile?z.locateFile(a,F):F+a}var na,H,fs,oa,pa;
if(D){F=C?require("path").dirname(F)+"/":__dirname+"/";pa=()=>{oa||(fs=require("fs"),oa=require("path"))};na=function(b,c){pa();b=oa.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};H=b=>{b=na(b,!0);b.buffer||(b=new Uint8Array(b));return b};1<process.argv.length&&(A=process.argv[1].replace(/\\/g,"/"));ka=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof I))throw b;});process.on("unhandledRejection",function(b){throw b;});B=(b,c)=>{if(noExitRuntime)throw process.exitCode=
b,c;c instanceof I||J("exiting due to exception: "+c);process.exit(b)};z.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(la||C)C?F=self.location.href:"undefined"!=typeof document&&document.currentScript&&(F=document.currentScript.src),_scriptDir&&(F=_scriptDir),0!==F.indexOf("blob:")?F=
F.substr(0,F.replace(/[?#].*/,"").lastIndexOf("/")+1):F="",D||(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},C&&(H=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));D&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var qa=console.log.bind(console),ra=console.warn.bind(console);D&&(pa(),qa=a=>fs.writeSync(1,a+"\n"),ra=a=>fs.writeSync(2,a+"\n"));
var sa=z.print||qa,J=z.printErr||ra;Object.assign(z,ja);ja=null;z.arguments&&(ka=z.arguments);z.thisProgram&&(A=z.thisProgram);z.quit&&(B=z.quit);var K;z.wasmBinary&&(K=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!=typeof WebAssembly&&L("no native wasm support detected");var k,ta,ua=!1,va="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b){for(var c=b+NaN,f=b;a[f]&&!(f>=c);)++f;if(16<f-b&&a.buffer&&va)return va.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,f):a.subarray(b,f));for(c="";b<f;){var h=a[b++];if(h&128){var g=a[b++]&63;if(192==(h&224))c+=String.fromCharCode((h&31)<<6|g);else{var n=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|n:(h&7)<<18|g<<12|n<<6|a[b++]&63;65536>h?c+=String.fromCharCode(h):(h-=65536,c+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else c+=String.fromCharCode(h)}return c}
function xa(a){return a?wa(v(),a):""}function ya(a,b,c,f){if(0<f){f=c+f-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var n=a.charCodeAt(++h);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=f)break;b[c++]=g}else{if(2047>=g){if(c+1>=f)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=f)break;b[c++]=224|g>>12}else{if(c+3>=f)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function za(a){for(var b=0,c=0;c<a.length;++c){var f=a.charCodeAt(c);127>=f?b++:2047>=f?b+=2:55296<=f&&57343>=f?(b+=4,++c):b+=3}return b}var l,aa,ba,ca,da,fa;E&&(l=z.buffer);function t(a){l=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=new Int16Array(a);z.HEAP32=ca=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAPU32=da=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=fa=new Float64Array(a)}var Aa=z.INITIAL_MEMORY||67108864;
if(E)k=z.wasmMemory,l=z.buffer;else if(z.wasmMemory)k=z.wasmMemory;else if(k=new WebAssembly.Memory({initial:Aa/65536,maximum:32768,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw J("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),D&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");k&&(l=k.buffer);Aa=l.byteLength;t(l);var Ba,Ca=[],Da=[],Ea=[],Fa=[];function Ga(){var a=z.preRun.shift();Ca.unshift(a)}var M=0,Ha=null,N=null;function L(a){if(E)postMessage({cmd:"onAbort",arg:a});else if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";J(a);ua=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ia(a);throw a;}function Ia(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="stockfish.wasm";Ia()||(O=ma(O));
function Ja(){var a=O;try{if(a==O&&K)return new Uint8Array(K);if(H)return H(a);throw"both async and sync fetching of the wasm failed";}catch(b){L(b)}}function Ka(){return K||!la&&!C||"function"!=typeof fetch?Promise.resolve().then(function(){return Ja()}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}var La={};
function I(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ma(a){(a=Q.T[a])||L();Q.ea(a)}function Na(a){var b=Q.ka();if(!b)return 6;Q.Y.push(b);Q.T[a.S]=b;b.S=a.S;var c={cmd:"run",start_routine:a.pa,arg:a.ia,pthread_ptr:a.S};b.X=()=>{c.time=performance.now();b.postMessage(c,a.va)};b.loaded&&(b.X(),delete b.X);return 0}function Oa(a){if(E)return R(1,1,a);if(!noExitRuntime){Q.qa();if(z.onExit)z.onExit(a);ua=!0}B(a,new I(a))}
function Pa(a,b){if(!b&&E)throw Qa(a),"unwind";Oa(a)}function Ra(a){a instanceof I||"unwind"==a||B(1,a)}
var Q={U:[],Y:[],ha:[],T:{},la:function(){E?Q.na():Q.ma()},ma:function(){for(var a=1;a--;)Q.ba()},na:function(){Q.receiveObjectTransfer=Q.oa;Q.threadInitTLS=Q.ga;Q.setExitStatus=Q.fa;noExitRuntime=!1},fa:function(){},qa:function(){for(var a of Object.values(Q.T))Q.ea(a);for(a of Q.U)a.terminate();Q.U=[]},ea:function(a){var b=a.S;delete Q.T[b];Q.U.push(a);Q.Y.splice(Q.Y.indexOf(a),1);a.S=0;Sa(b)},oa:function(){},ga:function(){Q.ha.forEach(a=>a())},da:function(a,b){a.onmessage=c=>{c=c.data;var f=c.cmd;
a.S&&(Q.ja=a.S);if(c.targetThread&&c.targetThread!=S()){var h=Q.T[c.xa];h?h.postMessage(c,c.transferList):J('Internal error! Worker sent a message "'+f+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===f)Ta(c.queue);else if("spawnThread"===f)Na(c);else if("cleanupThread"===f)Ma(c.thread);else if("killThread"===f)c=c.thread,f=Q.T[c],delete Q.T[c],f.terminate(),Sa(c),Q.Y.splice(Q.Y.indexOf(f),1),f.S=0;else if("cancelThread"===f)Q.T[c.thread].postMessage({cmd:"cancel"});
else if("loaded"===f)a.loaded=!0,b&&b(a),a.X&&(a.X(),delete a.X);else if("print"===f)sa("Thread "+c.threadId+": "+c.text);else if("printErr"===f)J("Thread "+c.threadId+": "+c.text);else if("alert"===f)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===f){if(z.onAbort)z.onAbort(c.arg)}else f&&J("worker sent an unknown command "+f);Q.ja=void 0};a.onerror=c=>{J("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};D&&(a.on("message",
function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:k,wasmModule:ta})},ba:function(){var a=ma("stockfish.worker.js");Q.U.push(new Worker(a))},ka:function(){0==Q.U.length&&(Q.ba(),Q.da(Q.U[0]));return Q.U.pop()}};z.PThread=Q;function T(a){for(;0<a.length;)a.shift()(z)}function Ua(a){var b=Va();a=a();U(b);return a}
z.establishStackSpace=function(){var a=S(),b=w()[a+44>>2];a=w()[a+48>>2];Wa(b,b-a);U(b)};function Qa(a){if(E)return R(2,0,a);try{Pa(a)}catch(b){Ra(b)}}var V=[];z.invokeEntryPoint=function(a,b){var c=V[a];c||(a>=V.length&&(V.length=a+1),V[a]=c=Ba.get(a));a=c(b);noExitRuntime?Q.fa(a):Xa(a)};function Ya(a,b){d().set(a,b)}function Za(a,b,c,f){return E?R(3,1,a,b,c,f):$a(a,b,c,f)}
function $a(a,b,c,f){if("undefined"==typeof SharedArrayBuffer)return J("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var h=[];if(E&&0===h.length)return Za(a,b,c,f);a={pa:c,S:a,ia:f,va:h};return E?(a.wa="spawnThread",postMessage(a,h),0):Na(a)}function ab(a,b,c){return E?R(4,1,a,b,c):0}function bb(a,b,c){return E?R(5,1,a,b,c):0}function cb(a,b,c,f){if(E)return R(6,1,a,b,c,f)}
function Ta(a){Atomics.store(w(),a>>2,1);S()&&db(a);Atomics.compareExchange(w(),a>>2,1,0)}z.executeNotifiedProxyingQueue=Ta;var W,eb;eb=D?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:E?()=>performance.now()-z.__performance_now_clock_drift:()=>performance.now();function R(a,b){var c=arguments.length-2,f=arguments;return Ua(()=>{for(var h=X(8*c),g=h>>3,n=0;n<c;n++){var u=f[2+n];ea()[g+n]=u}return fb(a,c,h,b)})}var gb=[],hb={};
function ib(){if(!jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:A||"./this.program"},b;for(b in hb)void 0===hb[b]?delete a[b]:a[b]=hb[b];var c=[];for(b in a)c.push(b+"="+a[b]);jb=c}return jb}var jb;
function kb(a,b){if(E)return R(7,1,a,b);var c=0;ib().forEach(function(f,h){var g=b+c;h=y()[a+4*h>>2]=g;for(g=0;g<f.length;++g)d()[h++>>0]=f.charCodeAt(g);d()[h>>0]=0;c+=f.length+1});return 0}function lb(a,b){if(E)return R(8,1,a,b);var c=ib();y()[a>>2]=c.length;var f=0;c.forEach(function(h){f+=h.length+1});y()[b>>2]=f;return 0}function mb(a){return E?R(9,1,a):52}function nb(a,b,c,f){return E?R(10,1,a,b,c,f):52}function pb(a,b,c,f,h){return E?R(11,1,a,b,c,f,h):70}var qb=[null,[],[]];
function rb(a,b,c,f){if(E)return R(12,1,a,b,c,f);for(var h=0,g=0;g<c;g++){var n=y()[b>>2],u=y()[b+4>>2];b+=8;for(var x=0;x<u;x++){var m=v()[n+x],q=qb[a];0===m||10===m?((1===a?sa:J)(wa(q,0)),q.length=0):q.push(m)}h+=u}y()[f>>2]=h;return 0}function Y(a){return 0===a%4&&(0!==a%100||0===a%400)}var sb=[31,29,31,30,31,30,31,31,30,31,30,31],tb=[31,28,31,30,31,30,31,31,30,31,30,31];function ub(a){var b=Array(za(a)+1);ya(a,b,0,b.length);return b}
function vb(a,b,c,f){function h(e,p,r){for(e="number"==typeof e?e.toString():e||"";e.length<p;)e=r[0]+e;return e}function g(e,p){return h(e,p,"0")}function n(e,p){function r(ob){return 0>ob?-1:0<ob?1:0}var G;0===(G=r(e.getFullYear()-p.getFullYear()))&&0===(G=r(e.getMonth()-p.getMonth()))&&(G=r(e.getDate()-p.getDate()));return G}function u(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function x(e){var p=e.V;for(e=new Date((new Date(e.W+1900,0,1)).getTime());0<p;){var r=e.getMonth(),G=(Y(e.getFullYear())?sb:tb)[r];if(p>G-e.getDate())p-=G-e.getDate()+1,e.setDate(1),11>r?e.setMonth(r+1):(e.setMonth(0),e.setFullYear(e.getFullYear()+1));else{e.setDate(e.getDate()+p);break}}r=new Date(e.getFullYear()+1,0,4);p=u(new Date(e.getFullYear(),0,
4));r=u(r);return 0>=n(p,e)?0>=n(r,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var m=w()[f+40>>2];f={ta:w()[f>>2],sa:w()[f+4>>2],Z:w()[f+8>>2],aa:w()[f+12>>2],$:w()[f+16>>2],W:w()[f+20>>2],R:w()[f+24>>2],V:w()[f+28>>2],ya:w()[f+32>>2],ra:w()[f+36>>2],ua:m?xa(m):""};c=xa(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var P="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Z="January February March April May June July August September October November December".split(" ");m={"%a":function(e){return P[e.R].substring(0,3)},"%A":function(e){return P[e.R]},"%b":function(e){return Z[e.$].substring(0,
3)},"%B":function(e){return Z[e.$]},"%C":function(e){return g((e.W+1900)/100|0,2)},"%d":function(e){return g(e.aa,2)},"%e":function(e){return h(e.aa,2," ")},"%g":function(e){return x(e).toString().substring(2)},"%G":function(e){return x(e)},"%H":function(e){return g(e.Z,2)},"%I":function(e){e=e.Z;0==e?e=12:12<e&&(e-=12);return g(e,2)},"%j":function(e){for(var p=0,r=0;r<=e.$-1;p+=(Y(e.W+1900)?sb:tb)[r++]);return g(e.aa+p,3)},"%m":function(e){return g(e.$+1,2)},"%M":function(e){return g(e.sa,2)},"%n":function(){return"\n"},
"%p":function(e){return 0<=e.Z&&12>e.Z?"AM":"PM"},"%S":function(e){return g(e.ta,2)},"%t":function(){return"\t"},"%u":function(e){return e.R||7},"%U":function(e){return g(Math.floor((e.V+7-e.R)/7),2)},"%V":function(e){var p=Math.floor((e.V+7-(e.R+6)%7)/7);2>=(e.R+371-e.V-2)%7&&p++;if(p)53==p&&(r=(e.R+371-e.V)%7,4==r||3==r&&Y(e.W)||(p=1));else{p=52;var r=(e.R+7-e.V-1)%7;(4==r||5==r&&Y(e.W%400-1))&&p++}return g(p,2)},"%w":function(e){return e.R},"%W":function(e){return g(Math.floor((e.V+7-(e.R+6)%7)/
7),2)},"%y":function(e){return(e.W+1900).toString().substring(2)},"%Y":function(e){return e.W+1900},"%z":function(e){e=e.ra;var p=0<=e;e=Math.abs(e)/60;return(p?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.ua},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in m)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),m[q](f)));c=c.replace(/\0\0/g,"%");q=ub(c);if(q.length>b)return 0;Ya(q,a);return q.length-1}Q.la();
var wb=[null,Oa,Qa,Za,ab,bb,cb,kb,lb,mb,nb,pb,rb],yb={j:function(a){xb(a,!C,1,!la);Q.ga()},h:function(a){E?postMessage({cmd:"cleanupThread",thread:a}):Ma(a)},x:$a,g:ab,t:bb,u:cb,y:function(){return 2097152},l:function(){return!0},m:function(a,b,c,f){if(a==b)setTimeout(()=>Ta(f));else if(E)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:f});else{a=Q.T[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:f})}return 1},i:function(){return-1},b:function(){L("")},e:function(){if(!D&&
!C){var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";W||(W={});W[a]||(W[a]=1,D&&(a="warning: "+a),J(a))}},c:eb,k:function(a,b,c){v().copyWithin(a,b,b+c)},z:function(a,b,c){gb.length=b;c>>=3;for(var f=0;f<b;f++)gb[f]=ea()[c+f];return(0>a?La[-a-1]:wb[a]).apply(null,gb)},w:function(a){var b=v().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var f=b*(1+.2/c);f=Math.min(f,a+100663296);var h=
Math;f=Math.max(a,f);h=h.min.call(h,2147483648,f+(65536-f%65536)%65536);a:{try{k.grow(h-l.byteLength+65535>>>16);t(k.buffer);var g=1;break a}catch(n){}g=void 0}if(g)return!0}return!1},r:function(){throw"unwind";},p:kb,q:lb,d:Pa,f:mb,s:nb,n:pb,v:rb,a:k||z.wasmMemory,o:function(a,b,c,f){return vb(a,b,c,f)}};
(function(){function a(h,g){z.asm=h.exports;Q.ha.push(z.asm.D);Ba=z.asm.L;Da.unshift(z.asm.A);ta=g;if(!E){var n=Q.U.length;Q.U.forEach(function(u){Q.da(u,function(){if(!--n&&(M--,z.monitorRunDependencies&&z.monitorRunDependencies(M),0==M&&(null!==Ha&&(clearInterval(Ha),Ha=null),N))){var x=N;N=null;x()}})})}}function b(h){a(h.instance,h.module)}function c(h){return Ka().then(function(g){return WebAssembly.instantiate(g,f)}).then(function(g){return g}).then(h,function(g){J("failed to asynchronously prepare wasm: "+
g);L(g)})}var f={a:yb};E||(M++,z.monitorRunDependencies&&z.monitorRunDependencies(M));if(z.instantiateWasm)try{return z.instantiateWasm(f,a)}catch(h){return J("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return K||"function"!=typeof WebAssembly.instantiateStreaming||Ia()||D||"function"!=typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(b,function(g){J("wasm streaming compile failed: "+g);J("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(ia);return{}})();z.___wasm_call_ctors=function(){return(z.___wasm_call_ctors=z.asm.A).apply(null,arguments)};z._main=function(){return(z._main=z.asm.B).apply(null,arguments)};z._uci_command=function(){return(z._uci_command=z.asm.C).apply(null,arguments)};z.__emscripten_tls_init=function(){return(z.__emscripten_tls_init=z.asm.D).apply(null,arguments)};
var S=z._pthread_self=function(){return(S=z._pthread_self=z.asm.E).apply(null,arguments)},xb=z.__emscripten_thread_init=function(){return(xb=z.__emscripten_thread_init=z.asm.F).apply(null,arguments)};z.__emscripten_thread_crashed=function(){return(z.__emscripten_thread_crashed=z.asm.G).apply(null,arguments)};
var fb=z._emscripten_run_in_main_runtime_thread_js=function(){return(fb=z._emscripten_run_in_main_runtime_thread_js=z.asm.H).apply(null,arguments)},db=z.__emscripten_proxy_execute_task_queue=function(){return(db=z.__emscripten_proxy_execute_task_queue=z.asm.I).apply(null,arguments)},Sa=z.__emscripten_thread_free_data=function(){return(Sa=z.__emscripten_thread_free_data=z.asm.J).apply(null,arguments)},Xa=z.__emscripten_thread_exit=function(){return(Xa=z.__emscripten_thread_exit=z.asm.K).apply(null,
arguments)},Wa=z._emscripten_stack_set_limits=function(){return(Wa=z._emscripten_stack_set_limits=z.asm.M).apply(null,arguments)},Va=z.stackSave=function(){return(Va=z.stackSave=z.asm.N).apply(null,arguments)},U=z.stackRestore=function(){return(U=z.stackRestore=z.asm.O).apply(null,arguments)},X=z.stackAlloc=function(){return(X=z.stackAlloc=z.asm.P).apply(null,arguments)};z.keepRuntimeAlive=function(){return noExitRuntime};z.wasmMemory=k;
z.ccall=function(a,b,c,f){var h={string:m=>{var q=0;if(null!==m&&void 0!==m&&0!==m){var P=(m.length<<2)+1,Z=q=X(P);ya(m,v(),Z,P)}return q},array:m=>{var q=X(m.length);Ya(m,q);return q}};a=z["_"+a];var g=[],n=0;if(f)for(var u=0;u<f.length;u++){var x=h[c[u]];x?(0===n&&(n=Va()),g[u]=x(f[u])):g[u]=f[u]}c=a.apply(null,g);return c=function(m){0!==n&&U(n);return"string"===b?xa(m):"boolean"===b?!!m:m}(c)};z.ExitStatus=I;z.PThread=Q;var zb;N=function Ab(){zb||Bb();zb||(N=Ab)};
function Cb(a){var b=z._main;a=a||[];a.unshift(A);var c=a.length,f=X(4*(c+1)),h=f>>2;a.forEach(n=>{var u=w(),x=h++,m=za(n)+1,q=X(m);ya(n,d(),q,m);u[x]=q});w()[h]=0;try{var g=b(c,f);Pa(g,!0)}catch(n){Ra(n)}}
function Bb(){function a(){if(!zb&&(zb=!0,z.calledRun=!0,!ua)){E||T(Da);E||T(Ea);ha(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();Db&&Cb(b);if(!E){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var c=z.postRun.shift();Fa.unshift(c)}T(Fa)}}}var b=b||ka;if(!(0<M))if(E)ha(z),E||T(Da),postMessage({cmd:"loaded"});else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ga();T(Ca);0<M||(z.setStatus?(z.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){z.setStatus("")},1);a()},1)):a())}}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var Db=!0;z.noInitialRun&&(Db=!1);Bb();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
