
var Stockfish = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


function d(){k.buffer!=m&&t(k.buffer);return aa}function v(){k.buffer!=m&&t(k.buffer);return ba}function w(){k.buffer!=m&&t(k.buffer);return ca}function y(){k.buffer!=m&&t(k.buffer);return da}function ea(){k.buffer!=m&&t(k.buffer);return fa}null;var z;z||(z=typeof Stockfish !== 'undefined' ? Stockfish : {});var ha,ia;z.ready=new Promise(function(a,b){ha=a;ia=b});
(function(){function a(){var g=f.shift();if(!b&&void 0!==g){if("quit"===g)return z.terminate();var l=z.ccall("uci_command","number",["string"],[g]);l&&f.unshift(g);h=l?2*h:1;setTimeout(a,h)}}var b=!1,c=[];z.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var l=0;l<c.length;l++)c[l](g)})};z.addMessageListener=function(g){c.push(g)};z.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};z.terminate=function(){b=!0;A.ja()};var f=[],h=1;z.postMessage=function(g){f.push(g)};
z.postRun=function(){z.postMessage=function(g){f.push(g);1===f.length&&a()};a()}})();var ja=Object.assign({},z),ka=[],B="./this.program",C=(a,b)=>{throw b;},la="object"==typeof window,D="function"==typeof importScripts,E="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,F=z.ENVIRONMENT_IS_PTHREAD||!1,H="";function ma(a){return z.locateFile?z.locateFile(a,H):H+a}var na,I,fs,oa,pa;
if(E){H=D?require("path").dirname(H)+"/":__dirname+"/";pa=()=>{oa||(fs=require("fs"),oa=require("path"))};na=function(b,c){pa();b=oa.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};I=b=>{b=na(b,!0);b.buffer||(b=new Uint8Array(b));return b};1<process.argv.length&&(B=process.argv[1].replace(/\\/g,"/"));ka=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof J))throw b;});process.on("unhandledRejection",function(b){throw b;});C=(b,c)=>{if(noExitRuntime)throw process.exitCode=
b,c;c instanceof J||K("exiting due to exception: "+c);process.exit(b)};z.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(la||D)D?H=self.location.href:"undefined"!=typeof document&&document.currentScript&&(H=document.currentScript.src),_scriptDir&&(H=_scriptDir),0!==H.indexOf("blob:")?H=
H.substr(0,H.replace(/[?#].*/,"").lastIndexOf("/")+1):H="",E||(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},D&&(I=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));E&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var qa=console.log.bind(console),ra=console.warn.bind(console);E&&(pa(),qa=a=>fs.writeSync(1,a+"\n"),ra=a=>fs.writeSync(2,a+"\n"));
var sa=z.print||qa,K=z.printErr||ra;Object.assign(z,ja);ja=null;z.arguments&&(ka=z.arguments);z.thisProgram&&(B=z.thisProgram);z.quit&&(C=z.quit);var L,M;z.wasmBinary&&(M=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!=typeof WebAssembly&&N("no native wasm support detected");var k,ta,ua=!1,va="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function wa(a,b){b>>>=0;for(var c=b+NaN,f=b;a[f]&&!(f>=c);)++f;if(16<f-b&&a.buffer&&va)return va.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,f):a.subarray(b,f));for(c="";b<f;){var h=a[b++];if(h&128){var g=a[b++]&63;if(192==(h&224))c+=String.fromCharCode((h&31)<<6|g);else{var l=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|l:(h&7)<<18|g<<12|l<<6|a[b++]&63;65536>h?c+=String.fromCharCode(h):(h-=65536,c+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else c+=String.fromCharCode(h)}return c}
function xa(a){return(a>>>=0)?wa(v(),a):""}function ya(a,b,c,f){c>>>=0;if(0<f){f=c+f-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=f)break;b[c++>>>0]=g}else{if(2047>=g){if(c+1>=f)break;b[c++>>>0]=192|g>>6}else{if(65535>=g){if(c+2>=f)break;b[c++>>>0]=224|g>>12}else{if(c+3>=f)break;b[c++>>>0]=240|g>>18;b[c++>>>0]=128|g>>12&63}b[c++>>>0]=128|g>>6&63}b[c++>>>0]=128|g&63}}b[c>>>0]=0}}
function za(a){for(var b=0,c=0;c<a.length;++c){var f=a.charCodeAt(c);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++c)&1023);127>=f?++b:b=2047>=f?b+2:65535>=f?b+3:b+4}return b}function Aa(a,b){d().set(a,b>>>0)}var m,aa,ba,ca,da,fa;F&&(m=z.buffer);
function t(a){m=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=new Int16Array(a);z.HEAP32=ca=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAPU32=da=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=fa=new Float64Array(a)}var Ba=z.INITIAL_MEMORY||1073741824;
if(F)k=z.wasmMemory,m=z.buffer;else if(z.wasmMemory)k=z.wasmMemory;else if(k=new WebAssembly.Memory({initial:Ba/65536,maximum:65536,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw K("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),E&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");k&&(m=k.buffer);Ba=m.byteLength;t(m);var Ca,Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=z.preRun.shift();Da.unshift(a)}var O=0,Ia=null,Q=null;function N(a){if(F)postMessage({cmd:"onAbort",arg:a});else if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";K(a);ua=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ia(a);throw a;}function Ja(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="stockfish.wasm";Ja()||(R=ma(R));
function Ka(){var a=R;try{if(a==R&&M)return new Uint8Array(M);if(I)return I(a);throw"both async and sync fetching of the wasm failed";}catch(b){N(b)}}function La(){return M||!la&&!D||"function"!=typeof fetch?Promise.resolve().then(function(){return Ka()}):fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return Ka()})}var Ma={};function Na(a){(a=A.R[a])||N();A.ha(a.worker)}
function Oa(a){var b=A.na();if(!b)return 6;A.Z.push(b);var c=A.R[a.da]={worker:b,ka:a.da};b.X=c;var f={cmd:"run",start_routine:a.sa,arg:a.W,threadInfoStruct:a.da};b.Y=()=>{f.time=performance.now();b.postMessage(f,a.xa)};b.loaded&&(b.Y(),delete b.Y);return 0}function Pa(a){a instanceof J||"unwind"==a||C(1,a)}
var A={T:[],Z:[],$:[],oa:function(){F?A.qa():A.pa()},pa:function(){for(var a=0;1>a;++a)A.fa()},qa:function(){A.receiveObjectTransfer=A.ra;A.threadInitTLS=A.la;A.setExitStatus=A.ia;noExitRuntime=!1},R:{},ia:function(){},ja:function(){for(var a in A.R){var b=A.R[a];b&&b.worker&&A.ha(b.worker)}for(a=0;a<A.T.length;++a)A.T[a].terminate();A.T=[]},ha:function(a){var b=a.X.ka;delete A.R[b];A.T.push(a);A.Z.splice(A.Z.indexOf(a),1);a.X=void 0;Qa(b)},ra:function(){},la:function(){for(var a in A.$)if(A.$.hasOwnProperty(a))A.$[a]()},
ga:function(a,b){a.onmessage=c=>{c=c.data;var f=c.cmd;a.X&&(A.ma=a.X.ka);if(c.targetThread&&c.targetThread!=S()){var h=A.R[c.Aa];h?h.worker.postMessage(c,c.transferList):K('Internal error! Worker sent a message "'+f+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===f)Ra(c.queue);else if("spawnThread"===f)Oa(c);else if("cleanupThread"===f)Na(c.thread);else if("killThread"===f)c=c.thread,f=A.R[c],delete A.R[c],f.worker.terminate(),Qa(c),A.Z.splice(A.Z.indexOf(f.worker),
1),f.worker.X=void 0;else if("cancelThread"===f)A.R[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===f)a.loaded=!0,b&&b(a),a.Y&&(a.Y(),delete a.Y);else if("print"===f)sa("Thread "+c.threadId+": "+c.text);else if("printErr"===f)K("Thread "+c.threadId+": "+c.text);else if("alert"===f)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===f){if(z.onAbort)z.onAbort(c.arg)}else f&&K("worker sent an unknown command "+f);A.ma=void 0};
a.onerror=c=>{K("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};E&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:k,wasmModule:ta})},fa:function(){var a=ma("stockfish.worker.js");A.T.push(new Worker(a))},na:function(){0==A.T.length&&(A.fa(),A.ga(A.T[0]));return A.T.pop()}};z.PThread=A;
function T(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(z);else{var c=b.za;"number"==typeof c?void 0===b.W?Sa(c)():Sa(c)(b.W):c(void 0===b.W?null:b.W)}}}function Ta(a){var b=Ua();a=a();U(b);return a}z.establishStackSpace=function(){var a=S(),b=w()[a+44>>2>>>0];a=w()[a+48>>2>>>0];Va(b,b-a);U(b)};function Wa(a){if(F)return V(1,0,a);try{Xa(a)}catch(b){Pa(b)}}var W=[];function Sa(a){var b=W[a];b||(a>=W.length&&(W.length=a+1),W[a]=b=Ca.get(a));return b}
z.invokeEntryPoint=function(a,b){a=Sa(a)(b);noExitRuntime?A.ia(a):Ya(a)};function Za(a,b,c,f){return F?V(2,1,a,b,c,f):$a(a,b,c,f)}function $a(a,b,c,f){if("undefined"==typeof SharedArrayBuffer)return K("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var h=[];if(F&&0===h.length)return Za(a,b,c,f);a={sa:c,da:a,W:f,xa:h};return F?(a.ya="spawnThread",postMessage(a,h),0):Oa(a)}function ab(a,b,c){return F?V(3,1,a,b,c):0}
function bb(a,b,c){return F?V(4,1,a,b,c):0}function cb(a,b,c,f){if(F)return V(5,1,a,b,c,f)}function Ra(a){Atomics.store(w(),a>>2,1);S()&&db(a);Atomics.compareExchange(w(),a>>2,1,0)}z.executeNotifiedProxyingQueue=Ra;var eb;eb=E?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:F?()=>performance.now()-z.__performance_now_clock_drift:()=>performance.now();
function V(a,b){var c=arguments.length-2,f=arguments;return Ta(function(){for(var h=X(8*c),g=h>>3,l=0;l<c;l++){var u=f[2+l];ea()[g+l>>>0]=u}return fb(a,c,h,b)})}var gb=[],hb={};
function ib(){if(!jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:B||"./this.program"},b;for(b in hb)void 0===hb[b]?delete a[b]:a[b]=hb[b];var c=[];for(b in a)c.push(b+"="+a[b]);jb=c}return jb}var jb;
function kb(a,b){if(F)return V(6,1,a,b);var c=0;ib().forEach(function(f,h){var g=b+c;h=y()[a+4*h>>2>>>0]=g;for(g=0;g<f.length;++g)d()[h++>>0>>>0]=f.charCodeAt(g);d()[h>>0>>>0]=0;c+=f.length+1});return 0}function lb(a,b){if(F)return V(7,1,a,b);var c=ib();y()[a>>2>>>0]=c.length;var f=0;c.forEach(function(h){f+=h.length+1});y()[b>>2>>>0]=f;return 0}function mb(a){return F?V(8,1,a):52}function nb(a,b,c,f){return F?V(9,1,a,b,c,f):52}function ob(a,b,c,f,h){return F?V(10,1,a,b,c,f,h):70}
var qb=[null,[],[]];function rb(a,b,c,f){if(F)return V(11,1,a,b,c,f);for(var h=0,g=0;g<c;g++){var l=y()[b>>2>>>0],u=y()[b+4>>2>>>0];b+=8;for(var x=0;x<u;x++){var n=v()[l+x>>>0],q=qb[a];0===n||10===n?((1===a?sa:K)(wa(q,0)),q.length=0):q.push(n)}h+=u}y()[f>>2>>>0]=h;return 0}function Y(a){return 0===a%4&&(0!==a%100||0===a%400)}var sb=[31,29,31,30,31,30,31,31,30,31,30,31],tb=[31,28,31,30,31,30,31,31,30,31,30,31];
function ub(a,b,c,f){function h(e,p,r){for(e="number"==typeof e?e.toString():e||"";e.length<p;)e=r[0]+e;return e}function g(e,p){return h(e,p,"0")}function l(e,p){function r(pb){return 0>pb?-1:0<pb?1:0}var G;0===(G=r(e.getFullYear()-p.getFullYear()))&&0===(G=r(e.getMonth()-p.getMonth()))&&(G=r(e.getDate()-p.getDate()));return G}function u(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function x(e){var p=e.U;for(e=new Date((new Date(e.V+1900,0,1)).getTime());0<p;){var r=e.getMonth(),G=(Y(e.getFullYear())?sb:tb)[r];if(p>G-e.getDate())p-=G-e.getDate()+1,e.setDate(1),11>r?e.setMonth(r+1):(e.setMonth(0),e.setFullYear(e.getFullYear()+1));else{e.setDate(e.getDate()+p);break}}r=new Date(e.getFullYear()+1,0,4);p=u(new Date(e.getFullYear(),0,
4));r=u(r);return 0>=l(p,e)?0>=l(r,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var n=w()[f+40>>2>>>0];f={va:w()[f>>2>>>0],ua:w()[f+4>>2>>>0],aa:w()[f+8>>2>>>0],ea:w()[f+12>>2>>>0],ba:w()[f+16>>2>>>0],V:w()[f+20>>2>>>0],S:w()[f+24>>2>>>0],U:w()[f+28>>2>>>0],Ba:w()[f+32>>2>>>0],ta:w()[f+36>>2>>>0],wa:n?xa(n):""};c=xa(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C",
"%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var P="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Z="January February March April May June July August September October November December".split(" ");n={"%a":function(e){return P[e.S].substring(0,3)},"%A":function(e){return P[e.S]},
"%b":function(e){return Z[e.ba].substring(0,3)},"%B":function(e){return Z[e.ba]},"%C":function(e){return g((e.V+1900)/100|0,2)},"%d":function(e){return g(e.ea,2)},"%e":function(e){return h(e.ea,2," ")},"%g":function(e){return x(e).toString().substring(2)},"%G":function(e){return x(e)},"%H":function(e){return g(e.aa,2)},"%I":function(e){e=e.aa;0==e?e=12:12<e&&(e-=12);return g(e,2)},"%j":function(e){for(var p=0,r=0;r<=e.ba-1;p+=(Y(e.V+1900)?sb:tb)[r++]);return g(e.ea+p,3)},"%m":function(e){return g(e.ba+
1,2)},"%M":function(e){return g(e.ua,2)},"%n":function(){return"\n"},"%p":function(e){return 0<=e.aa&&12>e.aa?"AM":"PM"},"%S":function(e){return g(e.va,2)},"%t":function(){return"\t"},"%u":function(e){return e.S||7},"%U":function(e){return g(Math.floor((e.U+7-e.S)/7),2)},"%V":function(e){var p=Math.floor((e.U+7-(e.S+6)%7)/7);2>=(e.S+371-e.U-2)%7&&p++;if(p)53==p&&(r=(e.S+371-e.U)%7,4==r||3==r&&Y(e.V)||(p=1));else{p=52;var r=(e.S+7-e.U-1)%7;(4==r||5==r&&Y(e.V%400-1))&&p++}return g(p,2)},"%w":function(e){return e.S},
"%W":function(e){return g(Math.floor((e.U+7-(e.S+6)%7)/7),2)},"%y":function(e){return(e.V+1900).toString().substring(2)},"%Y":function(e){return e.V+1900},"%z":function(e){e=e.ta;var p=0<=e;e=Math.abs(e)/60;return(p?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.wa},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](f)));c=c.replace(/\0\0/g,"%");q=vb(c);if(q.length>b)return 0;Aa(q,a);return q.length-
1}A.oa();var wb=[null,Wa,Za,ab,bb,cb,kb,lb,mb,nb,ob,rb];function vb(a){var b=Array(za(a)+1);ya(a,b,0,b.length);return b}
var yb={j:function(a){xb(a,!D,1,!la);A.la()},h:function(a){F?postMessage({cmd:"cleanupThread",thread:a}):Na(a)},x:$a,g:ab,t:bb,u:cb,y:function(){return 2097152},l:function(){return!0},m:function(a,b,c,f){if(a==b)setTimeout(()=>Ra(f));else if(F)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:f});else{a=(a=A.R[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:f})}return 1},i:function(){return-1},b:function(){N("")},e:function(){E||D||(L||(L={}),L["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(L["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,K("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},c:eb,k:function(a,b,c){v().copyWithin(a>>>0,b>>>0,b+c>>>0)},z:function(a,b,c){gb.length=b;c>>=3;for(var f=0;f<b;f++)gb[f]=ea()[c+f>>>0];return(0>a?Ma[-a-1]:wb[a]).apply(null,gb)},w:function(a){var b=v().length;a>>>=
0;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var f=b*(1+.2/c);f=Math.min(f,a+100663296);var h=Math;f=Math.max(a,f);h=h.min.call(h,4294901760,f+(65536-f%65536)%65536);a:{try{k.grow(h-m.byteLength+65535>>>16);t(k.buffer);var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},r:function(){throw"unwind";},p:kb,q:lb,d:function(a){Xa(a)},f:mb,s:nb,n:ob,v:rb,a:k||z.wasmMemory,o:function(a,b,c,f){return ub(a,b,c,f)}};
(function(){function a(h,g){z.asm=h.exports;A.$.push(z.asm.D);Ca=z.asm.L;Ea.unshift(z.asm.A);ta=g;if(!F){var l=A.T.length;A.T.forEach(function(u){A.ga(u,function(){if(!--l&&(O--,z.monitorRunDependencies&&z.monitorRunDependencies(O),0==O&&(null!==Ia&&(clearInterval(Ia),Ia=null),Q))){var x=Q;Q=null;x()}})})}}function b(h){a(h.instance,h.module)}function c(h){return La().then(function(g){return WebAssembly.instantiate(g,f)}).then(function(g){return g}).then(h,function(g){K("failed to asynchronously prepare wasm: "+
g);N(g)})}var f={a:yb};F||(O++,z.monitorRunDependencies&&z.monitorRunDependencies(O));if(z.instantiateWasm)try{return z.instantiateWasm(f,a)}catch(h){return K("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return M||"function"!=typeof WebAssembly.instantiateStreaming||Ja()||E||"function"!=typeof fetch?c(b):fetch(R,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(b,function(g){K("wasm streaming compile failed: "+g);K("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(ia);return{}})();z.___wasm_call_ctors=function(){return(z.___wasm_call_ctors=z.asm.A).apply(null,arguments)};z._main=function(){return(z._main=z.asm.B).apply(null,arguments)};z._uci_command=function(){return(z._uci_command=z.asm.C).apply(null,arguments)};z.__emscripten_tls_init=function(){return(z.__emscripten_tls_init=z.asm.D).apply(null,arguments)};
var S=z._pthread_self=function(){return(S=z._pthread_self=z.asm.E).apply(null,arguments)},xb=z.__emscripten_thread_init=function(){return(xb=z.__emscripten_thread_init=z.asm.F).apply(null,arguments)};z.__emscripten_thread_crashed=function(){return(z.__emscripten_thread_crashed=z.asm.G).apply(null,arguments)};
var fb=z._emscripten_run_in_main_runtime_thread_js=function(){return(fb=z._emscripten_run_in_main_runtime_thread_js=z.asm.H).apply(null,arguments)},db=z.__emscripten_proxy_execute_task_queue=function(){return(db=z.__emscripten_proxy_execute_task_queue=z.asm.I).apply(null,arguments)},Qa=z.__emscripten_thread_free_data=function(){return(Qa=z.__emscripten_thread_free_data=z.asm.J).apply(null,arguments)},Ya=z.__emscripten_thread_exit=function(){return(Ya=z.__emscripten_thread_exit=z.asm.K).apply(null,
arguments)},Va=z._emscripten_stack_set_limits=function(){return(Va=z._emscripten_stack_set_limits=z.asm.M).apply(null,arguments)},Ua=z.stackSave=function(){return(Ua=z.stackSave=z.asm.N).apply(null,arguments)},U=z.stackRestore=function(){return(U=z.stackRestore=z.asm.O).apply(null,arguments)},X=z.stackAlloc=function(){return(X=z.stackAlloc=z.asm.P).apply(null,arguments)};
z.ccall=function(a,b,c,f){var h={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var P=(n.length<<2)+1,Z=q=X(P);ya(n,v(),Z,P)}return q},array:function(n){var q=X(n.length);Aa(n,q);return q}};a=z["_"+a];var g=[],l=0;if(f)for(var u=0;u<f.length;u++){var x=h[c[u]];x?(0===l&&(l=Ua()),g[u]=x(f[u])):g[u]=f[u]}c=a.apply(null,g);return c=function(n){0!==l&&U(l);return"string"===b?xa(n):"boolean"===b?!!n:n}(c)};z.keepRuntimeAlive=function(){return noExitRuntime};z.wasmMemory=k;z.ExitStatus=J;
z.PThread=A;var zb;function J(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Q=function Ab(){zb||Bb();zb||(Q=Ab)};function Cb(a){var b=z._main;a=a||[];a.unshift(B);var c=a.length,f=X(4*(c+1)),h=f>>2;a.forEach(l=>{var u=w(),x=h++>>>0,n=za(l)+1,q=X(n);ya(l,d(),q,n);u[x]=q});w()[h>>>0]=0;try{var g=b(c,f);Xa(g,!0)}catch(l){Pa(l)}finally{}}
function Bb(a){function b(){if(!zb&&(zb=!0,z.calledRun=!0,!ua)){F||T(Ea);F||T(Fa);ha(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();Db&&Cb(a);if(!F){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var c=z.postRun.shift();Ga.unshift(c)}T(Ga)}}}a=a||ka;if(!(0<O))if(F)ha(z),F||T(Ea),postMessage({cmd:"loaded"});else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ha();T(Da);0<O||(z.setStatus?(z.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){z.setStatus("")},1);b()},1)):b())}}z.run=Bb;function Xa(a,b){if(!b&&F)throw Wa(a),"unwind";if(!noExitRuntime){A.ja();if(z.onExit)z.onExit(a);ua=!0}C(a,new J(a))}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var Db=!0;z.noInitialRun&&(Db=!1);Bb();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
