
var Stockfish = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


null;var c;c||(c=typeof Stockfish !== 'undefined' ? Stockfish : {});var aa,ba;c.ready=new Promise(function(a,b){aa=a;ba=b});null;(()=>{const a=[],b=[];c.print=d=>{a.push(d)};c.printErr=d=>{b.push(d)};c.message=()=>0<a.length?a.shift():null;c.errMessage=()=>0<b.length?b.shift():null;let e=[];c.postMessage=d=>{null!=e?e.push(d):c.ccall("uci_command","number",["string"],[d])};c.postRun=()=>{for(let d of e)c.ccall("uci_command","number",["string"],[d]);e=null}})();
var ca=Object.assign({},c),da=[],t="./this.program",v=(a,b)=>{throw b;},ea="object"==typeof window,w="function"==typeof importScripts,x="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,y="",fa,z,A,fs,C,ha;
if(x)y=w?require("path").dirname(y)+"/":__dirname+"/",ha=()=>{C||(fs=require("fs"),C=require("path"))},fa=function(a,b){ha();a=C.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},A=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},z=(a,b,e)=>{ha();a=C.normalize(a);fs.readFile(a,function(d,g){d?e(d):b(g.buffer)})},1<process.argv.length&&(t=process.argv[1].replace(/\\/g,"/")),da=process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
function(a){throw a;}),v=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof ia||D("exiting due to exception: "+b);process.exit(a)},c.inspect=function(){return"[Emscripten Module object]"};else if(ea||w)w?y=self.location.href:"undefined"!=typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.replace(/[?#].*/,"").lastIndexOf("/")+1):y="",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
w&&(A=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),z=(a,b,e)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):e()};d.onerror=e;d.send(null)};var ja=c.print||console.log.bind(console),D=c.printErr||console.warn.bind(console);Object.assign(c,ca);ca=null;c.arguments&&(da=c.arguments);c.thisProgram&&(t=c.thisProgram);c.quit&&(v=c.quit);
var E;c.wasmBinary&&(E=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!0;"object"!=typeof WebAssembly&&G("no native wasm support detected");var ka,H=!1,la="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b){for(var e=b+NaN,d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.buffer&&la)return la.decode(a.subarray(b,d));for(e="";b<d;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}
function na(a,b,e,d){if(0<d){d=e+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(e>=d)break;b[e++]=h}else{if(2047>=h){if(e+1>=d)break;b[e++]=192|h>>6}else{if(65535>=h){if(e+2>=d)break;b[e++]=224|h>>12}else{if(e+3>=d)break;b[e++]=240|h>>18;b[e++]=128|h>>12&63}b[e++]=128|h>>6&63}b[e++]=128|h&63}}b[e]=0}}
function oa(a){for(var b=0,e=0;e<a.length;++e){var d=a.charCodeAt(e);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++e):b+=3}return b}var pa,I,J,K,L;function qa(){var a=ka.buffer;pa=a;c.HEAP8=I=new Int8Array(a);c.HEAP16=new Int16Array(a);c.HEAP32=K=new Int32Array(a);c.HEAPU8=J=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=L=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[];
function wa(){var a=c.preRun.shift();sa.unshift(a)}var M=0,xa=null,N=null;function G(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";D(a);H=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function ya(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="stockfish.wasm";if(!ya()){var za=O;O=c.locateFile?c.locateFile(za,y):y+za}
function Aa(){var a=O;try{if(a==O&&E)return new Uint8Array(E);if(A)return A(a);throw"both async and sync fetching of the wasm failed";}catch(b){G(b)}}
function Ba(){if(!E&&(ea||w)){if("function"==typeof fetch&&!O.startsWith("file://"))return fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Aa()});if(z)return new Promise(function(a,b){z(O,function(e){a(new Uint8Array(e))},b)})}return Promise.resolve().then(function(){return Aa()})}function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ca(a){for(;0<a.length;)a.shift()(c)}function Da(a){a instanceof ia||"unwind"==a||v(1,a)}function Ea(a){this.H=a-24;this.U=function(b){L[this.H+4>>2]=b};this.R=function(b){L[this.H+8>>2]=b};this.S=function(){K[this.H>>2]=0};this.P=function(){I[this.H+12>>0]=0};this.T=function(){I[this.H+13>>0]=0};this.N=function(b,e){this.O();this.U(b);this.R(e);this.S();this.P();this.T()};this.O=function(){L[this.H+16>>2]=0}}var Fa=0;function Ga(a){if(!H)try{a()}catch(b){Da(b)}}
function Ha(a,b){setTimeout(function(){Ga(a)},b)}
function Ia(a,b){Ja=a;Ka=b;if(P)if(La||(La=!0),0==a)Q=function(){var d=Math.max(0,Ma+b-Na())|0;setTimeout(R,d)};else if(1==a)Q=function(){Oa(R)};else if(2==a){if("undefined"==typeof setImmediate){var e=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),e.shift()()},!0);setImmediate=function(d){e.push(d);w?(void 0===c.setImmediates&&(c.setImmediates=[]),c.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Q=function(){setImmediate(R)}}}var Na;Na=x?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Pa(a){if(!noExitRuntime){if(c.onExit)c.onExit(a);H=!0}v(a,new ia(a))}
function Qa(a){!P||G("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");P=a;var b=S;La=!1;R=function(){if(!H)if(0<Ra.length){var e=Date.now(),d=Ra.shift();d.ga(d.da);if(Sa){var g=Sa,h=0==g%1?g-1:Math.floor(g);Sa=d.ea?h:(8*g+(h+.5))/9}ja('main loop blocker "'+d.name+'" took '+(Date.now()-e)+" ms");c.setStatus&&(e=c.statusMessage||"Please wait...",d=Sa,g=Ta.fa,
d?d<g?c.setStatus(e+" ("+(g-d)+"/"+g+")"):c.setStatus(e):c.setStatus(""));b<S||setTimeout(R,0)}else b<S||(Ua=Ua+1|0,1==Ja&&1<Ka&&0!=Ua%Ka?Q():(0==Ja&&(Ma=Na()),H||c.preMainLoop&&!1===c.preMainLoop()||(Ga(a),c.postMainLoop&&c.postMainLoop()),b<S||("object"==typeof SDL&&SDL.audio&&SDL.audio.W&&SDL.audio.W(),Q())))}}function Va(a){Wa||(Wa={});Wa[a]||(Wa[a]=1,x&&(a="warning: "+a),D(a))}var Wa,La=!1,Q=null,S=0,P=null,Ja=0,Ka=0,Ua=0,Ra=[],Ta={},Ma,R,Sa,T=!1,Xa=!1,Ya=[];
function Za(){function a(){Xa=document.pointerLockElement===c.canvas||document.mozPointerLockElement===c.canvas||document.webkitPointerLockElement===c.canvas||document.msPointerLockElement===c.canvas}c.preloadPlugins||(c.preloadPlugins=[]);if(!$a){$a=!0;try{U=!0}catch(e){U=!1,D("warning: no blob constructor, cannot create blobs with mimetypes")}ab="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:U?null:D("warning: no BlobBuilder");V="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;c.M||"undefined"!=typeof V||(D("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),c.M=!0);c.preloadPlugins.push({canHandle:function(e){return!c.M&&/\.(jpg|jpeg|png|bmp)$/i.test(e)},handle:function(e,d,g,h){var l=null;if(U)try{l=new Blob([e],{type:bb(d)}),l.size!==e.length&&(l=new Blob([(new Uint8Array(e)).buffer],{type:bb(d)}))}catch(k){Va("Blob constructor present but fails: "+
k+"; falling back to blob builder")}l||(l=new ab,l.append((new Uint8Array(e)).buffer),l=l.getBlob());var p=V.createObjectURL(l),q=new Image;q.onload=()=>{q.complete||G("Image "+d+" could not be decoded");var k=document.createElement("canvas");k.width=q.width;k.height=q.height;k.getContext("2d").drawImage(q,0,0);V.revokeObjectURL(p);g&&g(e)};q.onerror=()=>{ja("Image "+p+" could not be decoded");h&&h()};q.src=p}});c.preloadPlugins.push({canHandle:function(e){return!c.ja&&e.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(e,d,g,h){function l(){q||(q=!0,g&&g(e))}function p(){q||(q=!0,new Audio,h&&h())}var q=!1;if(U){try{var k=new Blob([e],{type:bb(d)})}catch(u){return p()}k=V.createObjectURL(k);var m=new Audio;m.addEventListener("canplaythrough",()=>l(m),!1);m.onerror=function(){if(!q){D("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",B=0,f=0,n=0;n<e.length;n++)for(B=B<<8|e[n],f+=8;6<=f;){var r=B>>f-6&63;f-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==
f?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(B&3)<<4],u+="=="):4==f&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(B&15)<<2],u+="=");m.src="data:audio/x-"+d.substr(-3)+";base64,"+u;l(m)}};m.src=k;Ha(function(){l(m)},1E4)}else return p()}});var b=c.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),c.elementPointerLock&&b.addEventListener("click",e=>{!Xa&&c.canvas.requestPointerLock&&(c.canvas.requestPointerLock(),e.preventDefault())},!1))}}
function db(a,b,e,d){if(b&&c.L&&a==c.canvas)return c.L;var g;if(b){var h={antialias:!1,alpha:!1,ha:1};if(d)for(var l in d)h[l]=d[l];if("undefined"!=typeof GL&&(g=GL.createContext(a,h)))var p=GL.getContext(g).ba}else p=a.getContext("2d");if(!p)return null;e&&(b||"undefined"==typeof GLctx||G("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),c.L=p,b&&GL.ia(g),c.la=b,Ya.forEach(function(q){q()}),Za());return p}var eb=!1,fb=void 0,W=void 0;
function gb(a,b){function e(){T=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=hb,fb&&d.requestPointerLock(),T=!0,W?("undefined"!=typeof SDL&&(K[SDL.screen>>2]=L[SDL.screen>>2]|8388608),X(c.canvas),ib()):X(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),W?("undefined"!=typeof SDL&&(K[SDL.screen>>2]=L[SDL.screen>>2]&-8388609),
X(c.canvas),ib()):X(d));if(c.onFullScreen)c.onFullScreen(T);if(c.onFullscreen)c.onFullscreen(T)}fb=a;W=b;"undefined"==typeof fb&&(fb=!0);"undefined"==typeof W&&(W=!1);var d=c.canvas;eb||(eb=!0,document.addEventListener("fullscreenchange",e,!1),document.addEventListener("mozfullscreenchange",e,!1),document.addEventListener("webkitfullscreenchange",e,!1),document.addEventListener("MSFullscreenChange",e,!1));var g=document.createElement("div");d.parentNode.insertBefore(g,d);g.appendChild(d);g.requestFullscreen=
g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?()=>g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(g.webkitRequestFullScreen?()=>g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);g.requestFullscreen()}function hb(){if(!T)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Y=0;
function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Y)Y=b+1E3/60;else for(;b+2>=Y;)Y+=1E3/60;setTimeout(a,Math.max(Y-b,0))}}function jb(a){Oa(function(){Ga(a)})}function bb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var kb=[];function ib(){var a=c.canvas;kb.forEach(function(b){b(a.width,a.height)})}
function X(a,b,e){b&&e?(a.aa=b,a.V=e):(b=a.aa,e=a.V);var d=b,g=e;c.forcedAspectRatio&&0<c.forcedAspectRatio&&(d/g<c.forcedAspectRatio?d=Math.round(g*c.forcedAspectRatio):g=Math.round(d/c.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/g);d=Math.round(d*h);g=Math.round(g*h)}W?
(a.width!=d&&(a.width=d),a.height!=g&&(a.height=g),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(d!=b||g!=e?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",g+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var $a,U,ab,V,lb=[],mb={};
function nb(){if(!ob){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:t||"./this.program"},b;for(b in mb)void 0===mb[b]?delete a[b]:a[b]=mb[b];var e=[];for(b in a)e.push(b+"="+a[b]);ob=e}return ob}var ob,pb=[null,[],[]];function qb(a){return 0===a%4&&(0!==a%100||0===a%400)}
var rb=[31,29,31,30,31,30,31,31,30,31,30,31],sb=[31,28,31,30,31,30,31,31,30,31,30,31];function tb(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}
function ub(a,b,e,d){function g(f,n,r){for(f="number"==typeof f?f.toString():f||"";f.length<n;)f=r[0]+f;return f}function h(f,n){return g(f,n,"0")}function l(f,n){function r(cb){return 0>cb?-1:0<cb?1:0}var F;0===(F=r(f.getFullYear()-n.getFullYear()))&&0===(F=r(f.getMonth()-n.getMonth()))&&(F=r(f.getDate()-n.getDate()));return F}function p(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function q(f){var n=f.F;for(f=new Date((new Date(f.G+1900,0,1)).getTime());0<n;){var r=f.getMonth(),F=(qb(f.getFullYear())?rb:sb)[r];if(n>F-f.getDate())n-=F-f.getDate()+1,f.setDate(1),11>r?f.setMonth(r+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+n);break}}r=new Date(f.getFullYear()+1,0,4);n=p(new Date(f.getFullYear(),0,
4));r=p(r);return 0>=l(n,f)?0>=l(r,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var k=K[d+40>>2];d={Z:K[d>>2],Y:K[d+4>>2],I:K[d+8>>2],K:K[d+12>>2],J:K[d+16>>2],G:K[d+20>>2],D:K[d+24>>2],F:K[d+28>>2],ka:K[d+32>>2],X:K[d+36>>2],$:k?k?ma(J,k):"":""};e=e?ma(J,e):"";k={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var m in k)e=e.replace(new RegExp(m,"g"),k[m]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");k={"%a":function(f){return u[f.D].substring(0,3)},"%A":function(f){return u[f.D]},"%b":function(f){return B[f.J].substring(0,3)},
"%B":function(f){return B[f.J]},"%C":function(f){return h((f.G+1900)/100|0,2)},"%d":function(f){return h(f.K,2)},"%e":function(f){return g(f.K,2," ")},"%g":function(f){return q(f).toString().substring(2)},"%G":function(f){return q(f)},"%H":function(f){return h(f.I,2)},"%I":function(f){f=f.I;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){for(var n=0,r=0;r<=f.J-1;n+=(qb(f.G+1900)?rb:sb)[r++]);return h(f.K+n,3)},"%m":function(f){return h(f.J+1,2)},"%M":function(f){return h(f.Y,2)},"%n":function(){return"\n"},
"%p":function(f){return 0<=f.I&&12>f.I?"AM":"PM"},"%S":function(f){return h(f.Z,2)},"%t":function(){return"\t"},"%u":function(f){return f.D||7},"%U":function(f){return h(Math.floor((f.F+7-f.D)/7),2)},"%V":function(f){var n=Math.floor((f.F+7-(f.D+6)%7)/7);2>=(f.D+371-f.F-2)%7&&n++;if(n)53==n&&(r=(f.D+371-f.F)%7,4==r||3==r&&qb(f.G)||(n=1));else{n=52;var r=(f.D+7-f.F-1)%7;(4==r||5==r&&qb(f.G%400-1))&&n++}return h(n,2)},"%w":function(f){return f.D},"%W":function(f){return h(Math.floor((f.F+7-(f.D+6)%
7)/7),2)},"%y":function(f){return(f.G+1900).toString().substring(2)},"%Y":function(f){return f.G+1900},"%z":function(f){f=f.X;var n=0<=f;f=Math.abs(f)/60;return(n?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.$},"%%":function(){return"%"}};e=e.replace(/%%/g,"\x00\x00");for(m in k)e.includes(m)&&(e=e.replace(new RegExp(m,"g"),k[m](d)));e=e.replace(/\0\0/g,"%");m=tb(e);if(m.length>b)return 0;I.set(m,a);return m.length-1}c.requestFullscreen=function(a,b){gb(a,b)};
c.requestAnimationFrame=function(a){Oa(a)};c.setCanvasSize=function(a,b,e){X(c.canvas,a,b);e||ib()};c.pauseMainLoop=function(){Q=null;S++};c.resumeMainLoop=function(){S++;var a=Ja,b=Ka,e=P;P=null;Qa(e);Ia(a,b);Q()};c.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};c.createContext=function(a,b,e,d){return db(a,b,e,d)};
var wb={g:function(a){return vb(a+24)+24},f:function(a,b,e){(new Ea(a)).N(b,e);Fa++;throw a;},d:function(){return 0},s:function(){return 0},h:function(){},j:function(){return Date.now()},i:function(){return!0},c:function(){G("")},a:function(a,b,e){function d(){var g=lb[a];g||(a>=lb.length&&(lb.length=a+1),lb[a]=g=ra.get(a));g(b)}0<=e||x?Ha(d,e):jb(d)},k:function(a,b,e){J.copyWithin(a,b,b+e)},b:function(a){var b=J.length;a>>>=0;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var d=b*(1+.2/e);d=Math.min(d,
a+100663296);var g=Math;d=Math.max(a,d);g=g.min.call(g,2147483648,d+(65536-d%65536)%65536);a:{try{ka.grow(g-pa.byteLength+65535>>>16);qa();var h=1;break a}catch(l){}h=void 0}if(h)return!0}return!1},o:function(a,b){var e=0;nb().forEach(function(d,g){var h=b+e;g=L[a+4*g>>2]=h;for(h=0;h<d.length;++h)I[g++>>0]=d.charCodeAt(h);I[g>>0]=0;e+=d.length+1});return 0},p:function(a,b){var e=nb();L[a>>2]=e.length;var d=0;e.forEach(function(g){d+=g.length+1});L[b>>2]=d;return 0},l:Pa,e:function(){return 52},r:function(){return 52},
m:function(){return 70},q:function(a,b,e,d){for(var g=0,h=0;h<e;h++){var l=L[b>>2],p=L[b+4>>2];b+=8;for(var q=0;q<p;q++){var k=J[l+q],m=pb[a];0===k||10===k?((1===a?ja:D)(ma(m,0)),m.length=0):m.push(k)}g+=p}L[d>>2]=g;return 0},n:function(a,b,e,d){return ub(a,b,e,d)}};
(function(){function a(g){c.asm=g.exports;ka=c.asm.t;qa();ra=c.asm.y;ta.unshift(c.asm.u);M--;c.monitorRunDependencies&&c.monitorRunDependencies(M);0==M&&(null!==xa&&(clearInterval(xa),xa=null),N&&(g=N,N=null,g()))}function b(g){a(g.instance)}function e(g){return Ba().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(g,function(h){D("failed to asynchronously prepare wasm: "+h);G(h)})}var d={a:wb};M++;c.monitorRunDependencies&&c.monitorRunDependencies(M);if(c.instantiateWasm)try{return c.instantiateWasm(d,
a)}catch(g){return D("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return E||"function"!=typeof WebAssembly.instantiateStreaming||ya()||O.startsWith("file://")||x||"function"!=typeof fetch?e(b):fetch(O,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(h){D("wasm streaming compile failed: "+h);D("falling back to ArrayBuffer instantiation");return e(b)})})})().catch(ba);return{}})();
c.___wasm_call_ctors=function(){return(c.___wasm_call_ctors=c.asm.u).apply(null,arguments)};c._main=function(){return(c._main=c.asm.v).apply(null,arguments)};var vb=c._malloc=function(){return(vb=c._malloc=c.asm.w).apply(null,arguments)};c._uci_command=function(){return(c._uci_command=c.asm.x).apply(null,arguments)};
var xb=c.stackSave=function(){return(xb=c.stackSave=c.asm.z).apply(null,arguments)},yb=c.stackRestore=function(){return(yb=c.stackRestore=c.asm.A).apply(null,arguments)},Z=c.stackAlloc=function(){return(Z=c.stackAlloc=c.asm.B).apply(null,arguments)};c.___cxa_is_pointer_type=function(){return(c.___cxa_is_pointer_type=c.asm.C).apply(null,arguments)};
c.ccall=function(a,b,e,d){var g={string:k=>{var m=0;if(null!==k&&void 0!==k&&0!==k){var u=(k.length<<2)+1;m=Z(u);na(k,J,m,u)}return m},array:k=>{var m=Z(k.length);I.set(k,m);return m}};a=c["_"+a];var h=[],l=0;if(d)for(var p=0;p<d.length;p++){var q=g[e[p]];q?(0===l&&(l=xb()),h[p]=q(d[p])):h[p]=d[p]}e=a.apply(null,h);return e=function(k){0!==l&&yb(l);return"string"===b?k?ma(J,k):"":"boolean"===b?!!k:k}(e)};var zb;N=function Ab(){zb||Bb();zb||(N=Ab)};
function Cb(a){var b=c._main;a=a||[];a.unshift(t);var e=a.length,d=Z(4*(e+1)),g=d>>2;a.forEach(l=>{var p=K,q=g++,k=oa(l)+1,m=Z(k);na(l,I,m,k);p[q]=m});K[g]=0;try{var h=b(e,d);Pa(h,!0)}catch(l){Da(l)}}
function Bb(){function a(){if(!zb&&(zb=!0,c.calledRun=!0,!H)){Ca(ta);Ca(ua);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();Db&&Cb(b);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var e=c.postRun.shift();va.unshift(e)}Ca(va)}}var b=b||da;if(!(0<M)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)wa();Ca(sa);0<M||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},
1);a()},1)):a())}}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Db=!0;c.noInitialRun&&(Db=!1);Bb();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
